FROM python:3.11-alpine

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN pip install pytest

CMD sh -c '
psql postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-test_db} -c "CREATE DATABASE ${POSTGRES_TEST_DB:-test_db};" &&
pytest --disable-warnings
'